type: ch5

play_data:
  multi_process_num: 24
  nb_game_in_file: 1
  max_file_num: 800

play:
  simulation_num_per_move: 200
  share_mtcs_info_in_self_play: True
  reset_mtcs_info_per_game: 1
  thinking_loop: 10
  use_newest_next_generation_model: True

trainer:
  delete_self_play_after_number_of_training: 1
  min_data_size_to_learn: 1
  save_model_steps: 10
  wait_after_save_model_ratio: 0
